Calendar
js-tasks-ru/htmlcss-20210409_galchenkou pull request #14
Opened 2021-05-12 11:29 UTC by GalchenkoIurii

2021-05-12 11:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-13 12:21 UTC, GSemikozov requested changes

2021-05-13 12:21 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar-items__box {
по БЭМ - просто `.calendar__box`

2021-05-15 21:02 UTC, GalchenkoIurii commented on 05-lection3/03-calendar/calendar.css
> +.calendar-items__box {
спасибо, сделал. Там правда сверху был класс-обертка calendar__box, пришлось поменять на calendar-box

2021-05-15 21:04 UTC, closed without merging