added styles for buttons
js-tasks-ru/htmlcss-20210409_galchenkou pull request #5
Opened 2021-04-25 18:12 UTC by GalchenkoIurii

2021-04-25 18:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-04-25 18:36 UTC, GSemikozov requested changes

2021-04-25 18:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons-section {
Распишу все замечания в одном комментарии.
1. В файле блока должны быть стили касающиеся лишь этого блока, поэтому стили которые были добавлены для создания сетки, в которую встраиваются кнопки - их надо отсюда убрать, например, на страницу задачи прямо в тэг style в секции body - эти стили нужны нам лишь чтобы продемонстрировать решение и на самом проекте (на Главной странице и т.д.) они использоваться не будут.
2. Классы по типу `.buttons-box__item_text`  или `.buttons-box__item_btn` - прописаны неверно, не по БЭМ. По сути, это элементы своих блоков (тут - .buttons-box), а элементы мы пишем через двойное нижнее подчеркивание. Правильно было бы вот так: `.buttons-box__item-text`  или `.buttons-box__item-btn`. А через одно нижнее подчеркивание записывается модификатор (блока или элемента), который лишь как-то изменяет общие стили блока / элемента, но не является отдельной сущностью (блок / элемент).
3. По самим кнопкам - `.button_primary_hovered` такие модификаторы записаны во-первых неверно (их надо писать раздельно, `.button_primary` `.button_hovered`), во-вторых описывать состояния типа ховер или disabled классами не стоит, мы используем встроенные пвсевдоклассы :hover, :disabled, этого достаточно.
4. `.button_primary_disabled` -  указывать каждому типу кнопки одно и то же состояние disabled с одним и тем же стилем будет избыточным, лучше задать модификатор блоку кнопку без привязки к типу кнопки, вот так: `.button_disabled {}`, кроме того при состоянии disabled важно запретить пользователю нажимать на кнопку - `pointer-events: none`

2021-04-25 18:51 UTC, GalchenkoIurii commented on 03-lection1/01-button/button.css
> +.buttons-section {
Я думал что должен быть блок сверстан как в макете, чтобы :hover кнопки были показаны как будто в этом состоянии, а так получается они все будут одинаковые? только при наведении будут меняться? 
И еще вопрос по :disabled, их можно сделать неактивными через задание атрибута disabled тэгу button?

2021-04-27 07:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons-section {
да, форсить стейты не нужно, да данном этапе визуальную часть я не проверяю, только код)
да, верно, я не написал - но, обычно disabled задается через атрибут

2021-04-27 07:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons-section {
и не забываем про pointer-events: none

2021-04-28 07:34 UTC, GSemikozov approved these changes

2021-04-28 07:34 UTC, merged